### ISSUE TITLE
fix(guildinfo): there is rate limit but no cooldown 

### ISSUE THREAD

**Issue by Dhruvin-Purohit** [Dude-Perfect-Discord-Bot/Dude-Perfect#114]
Guild command has rate-limit but no cooldown, so no point.

**Comment by XynoxTheDev** [comment]
Yes, we will fix everything in the configurations of commands and make sure to release it by the next update.

**Comment by XynoxTheDev** [comment]
There is a default cooldown for each command. It will be removed from the command and the default one will be used.
