### ISSUE TITLE
bug(Voice Disconnect): Unexpected error response

### ISSUE THREAD

**Issue by XynoxTheDev** [Dude-Perfect-Discord-Bot/Dude-Perfect#124]
**Describe the bug**
A user is not present in the voice channel but then to bot is sending an error as well as a success message in response.

**To Reproduce**
1. Use the command on someone who is not connected to the voice channel.
2. Bot will respond with an error as well as a success message.

**Expected behavior**
The bot should only send the error message in response.

**Screenshots**
![image](https://user-images.githubusercontent.com/51535331/122053022-fc6a9800-ce03-11eb-94ef-ebe072134416.png)

**Additional context**
> (Prefer to use [Github Commits](https://www.conventionalcommits.org/en/v1.0.0/))

**Comment by Anish-Shobith** [comment]
Fixed in fddb025
