### ISSUE TITLE
Serverinfo not working 

### ISSUE THREAD

**Issue by XynoxTheDev** [Dude-Perfect-Discord-Bot/Dude-Perfect#21]
**Describe the bug**
Serverinfo not working unless we do userinfo of the owner. 

**Expected behavior**
The serverinfo should fetch data of the server so that no userinfo of the owner is required. 

**Version [2.1.4]**

**Comment by officialpiyush** [comment]
I doubt this has something to do with the Intents and/or cache, I'll check it out in the morning
